parameters:
    command_subscriber.class: OroTest\ChainCommandBundle\EventSubscriber\CommandSubscriber

services:
    oro_test_chain_command.command_subscriber:
        class: '%command_subscriber.class%'
        tags:
            - { name: kernel.event_subscriber }
